.github/PULL_REQUEST_TEMPLATE.md
docs/user-guide/quickstart.md

New providers have been added to Strands Agents. This PR adds them to the quickstart page. To reduce clutter in the quickstart section we removed all but the default provider, Bedrock. Instead we now provide a list of other providers which we will continue to add to.
Additionally, the contributing link was broken. So this PR synchronizes it with other repositories owned by the organization to just be text, and not a link.
New providers have been added and should be displayed front and center.
quickstart.md
Updated screenshot
nformation that is important to this PR -->

feat: add llama, ollama, and anthropic to quickstart in alphabetized order

---

mkdocs.yml

Forgot to add the link so that the page shows up on the sidebar on docs. Fixed it in this PR.

Add missing link in `mkdocs.yml` file

---

docs/user-guide/concepts/tools/example-tools-package.md
docs/user-guide/quickstart.md

Document additional example tools:
* memory
* mem0_memory
* cron
* slack
* speak
Include additional tools.
https://strandsagents.com/0.1.x/user-guide/concepts/tools/example-tools-package/

docs: add tools to example tools package page: memory, mem0_memory, cron, slack, speak

---

docs/user-guide/concepts/tools/example-tools-package.md

This PR fixes an inaccuracy in the "Available Tools" documentation, replacing "create AI generated images with Nova Reels" with "create AI generated videos with Nova Reels"
Amazon Nova Reels is a video generation model
Page: Example Built-in Tools
File: docs/user-guide/concepts/tools/example-tools-package.md
n/a
- [n/a] Links in the documentation are valid and working
- [n/a] Images/diagrams are properly sized and formatted
n/a

Fix inaccuracy in tools documentation

---

docs/user-guide/concepts/model-providers/amazon-bedrock.md

The Bedrock model provider docs describe the needed IAM policy as `bedrock-runtime:InvokeModelWithResponseStream`, but the actual IAM policy prefix is just `bedrock`.
- Bug fix
Couldn't get the basic examples to work with a dedicated, tightly-scoped role.
Bedrock Model Provider page

fix: Correction to IAM policy prefixes (bedrock: not bedrock-runtime:)

---

docs/user-guide/concepts/tools/mcp-tools.md

There's an incorrect parenthesis in the example
docs/user-guide/concepts/tools/mcp-tools.md

Fix parenthesis in mcp-tools

---

docs/examples/python/mcp_calculator.md

Resolves [#22](https://github.com/strands-agents/docs/issues/22)
Fixes the syntax of the direct agent tool call in the mcp calculator example to use `agent.tool.add` instead of `agent.add`. 
Bug fix
Fix the syntax in our public docs since the current example results in an error
https://strandsagents.com/0.1.x/examples/python/mcp_calculator/#explicit-tool-call-through-agent 
Tested with a python class as described in the mcp example. First tested with the unchanged syntax, which results in: 
```
Traceback (most recent call last):
File "/Users/shanaxml/workplace/strands_test.py", line 31, in <module>
agent.add(x=125, y=375)
AttributeError: 'Agent' object has no attribute 'add'
```
Then, after the change:
```
Calculation result: 500
```
By submitting this pull …

fix: Correct the syntax for mcp calculator tool call

---

.github/workflows/build-pages.yml

We've had internal requests to redirect to latest by default
It makes more sense that the root page redirects to latest rather than 0.1.x so that when folks copy links, they're copying the latest docs.
People can always manually change to a specific version
Try it out at https://github.programdotrun.com/docs/
Folks mentioned that linking to the latest docs page is difficult because they need to manually edit the url - now by default they'll get the latest urls and can manually change to 0.1.x if they so wish
The bare index url https://strandsagents.com/ would now redirect to https://strandsagents.com/latest/ instead of https://strandsagents.com/0.1.x/.  All other URLs will continue working
By submitting this pull request, I confirm that you can use, …

Set the default redirect to latest

---

docs/user-guide/concepts/model-providers/amazon-bedrock.md

Adding documentation for non-streaming support in bedrock
- Bug fix
New content addition
PR: https://github.com/strands-agents/sdk-python/pull/75
Bedrock model provider docs
N/A
N/A

Update docs to include non-streaming bedrock config

---

mkdocs.yml
requirements.txt

Using the mkdocs-llmstxt plugin, we can generate llms.txt which describes the project and points LLMs towards markdown twins of specific documentation hosted for humans as HTML. These twins are generated during the build process and served as *.md. See: https://llmstxt.org/ & https://pypi.org/project/mkdocs-llmstxt/
New mkdocs plugin and hosted content (llms.txt & *.md files)
Makes it easier for LLMs to understand Strands: https://llmstxt.org/
Changes mkdocs configuration and hosted content. 
- [x ] I have read the CONTRIBUTING document
- [x ] My changes follow the project's documentation style
- [x ] I have tested the documentation locally using `mkdocs serve`
- [x ] Links in the documentation are valid and working
- [x ] Images/diagrams are properly sized and formatted
- [x ] All new …

Serve llms.txt via mkdocs-llmstxt plugin

---

mkdocs.yml
requirements.txt

This commit appears to have broken the mermaid diagrams. We are reverting while we investigate.
Here is an example of what the diagrams look like now:
Fix broken mermaid diagrams.
Results after running `mkdocs build` locally with the commit reverted:

Revert "Serve llms.txt via mkdocs-llmstxt plugin (#72)"

---

docs/user-guide/deploy/deploy_to_aws_fargate.md

Correcting a typo in the docs as it is inconsistent with the remaining examples. 
- Typo/formatting fix in /user-guide/deploy/deploy_to_aws_fargate.md in section "## Creating Your Agent in Python" mentions a Flask application. While the referenced app in /examples/cdk/deploy_to_fargate/docker/app/app.py is using FastAPI library only
Typo/formatting
/user-guide/deploy/deploy_to_aws_fargate.md
This is a single word change from Flask to FastAPI

fixing inconsistent naming from Flask to FastAPI

---

docs/user-guide/concepts/model-providers/amazon-bedrock.md

Adding back documentation for non-streaming models
- Bug fix
New content addition
non-streaming support has been pushed, so adding the docs back
Bedrock model provider
N/A
N/A

Add back non-streaming docs

---

docs/examples/cdk/deploy_to_ec2/README.md
docs/examples/cdk/deploy_to_lambda/.mise.toml
docs/examples/cdk/deploy_to_lambda/README.md
docs/user-guide/deploy/deploy_to_amazon_ec2.md

For lambda and EC2, specify the python version so that the correct binaries will be installed. Fixes #64
Also removed the mise.toml to be more consistent with other examples.
Tested by defaulting my python to 3.11 and then running through the lambda readme.
Bug fix
#64 was a reported issue
Lambda & EC2 examples
N/A

fix: Specify python version for dependency installs

---

docs/user-guide/concepts/tools/tools_overview.md
docs/user-guide/safety-security/guardrails.md

Documents the bugfix implemented in strands-agents/sdk-python#178 where underscores take the place of hyphens
This is the docs PR for https://github.com/strands-agents/sdk-python/pull/178
Direct method invocation of tools

feat: Document invoking tools with hyphens

---

.github/workflows/build-pages.yml

We want to switch to manually building docs, so that we don't publish docs for bug fixes or doc changes before we publish to pypi
- Other: Feature/Refactor
The current situation:
- When a bugfix or feature is merged to the SDK, it doesn't get published to consumer until we publish to pypi
- When a doc change is merged to the SDK it's published immediately
This means that doc changes for bugs or features are published before the corresponding changes are ready to be consumed, leading to customer confusion.  Until we start branching for docs, we're going to switch to manually publishing docs
Doc publishing
Will need to update the MCM to account for this
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

feat: Switch to manually building docs

---

docs/user-guide/observability-evaluation/traces.md

Add warning for OTEL export support. 
Warn individuals for users who want to export traces to a collector backend.
Tracing.

docs: add otel export warning

---

docs/user-guide/concepts/model-providers/amazon-bedrock.md

The documentation currently uses the IAM prefix `bedrock-runtime:`,  
but the correct prefix is `bedrock:`.
References:
- [Actions, resources, and condition keys for AWS services](https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html)
- [Actions, resources, and condition keys for Amazon Bedrock](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonbedrock.html)
- [converse_stream](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-runtime/client/converse_stream.html)
- Bug fix
- - The "Getting Started" guide does not work due to the incorrect IAM prefix.
- Bedrock Model Provider page
By submitting this pull request, I confirm that you can …

fix incorrect bedrock iam prefix

---

docs/user-guide/concepts/tools/tools_overview.md

Fix typo in the code sample under MCP tools on Tools Overview page
- Bug fix
Typo/formatting fix
Tools Overview --> Building & Loading Tools --> 2. Model Context Protocol (MCP) Tools

fix typo in code example on MCP tools

---

docs/user-guide/observability-evaluation/traces.md

Update documentation based on the [PR](https://github.com/strands-agents/sdk-python/pull/286).
Users will follow the documentation to set up exporters and tracer.
Traces
NA

docs: update tracer setup documentation

---

docs/api-reference/event-loop.md

A recent change in the sdk caused the docs to fail building: https://github.com/strands-agents/sdk-python/commit/3ae8d77687f25e4cff1d1f7f2df6d0937c7a152a#diff-9e2c3161d4288440581ed5f678fcbae69b35d6b865fd6e67413fc61d9af13197
This change fixes that
- Bug fix
Fixes build issue
Removes: strands.event_loop.error_handler
N/A
We need a way to detect this in the sdk before merging

remove event_loop error_handler reference

---

docs/user-guide/concepts/model-providers/amazon-bedrock.md
docs/user-guide/concepts/model-providers/anthropic.md
docs/user-guide/concepts/model-providers/custom_model_provider.md
docs/user-guide/concepts/model-providers/litellm.md
docs/user-guide/concepts/model-providers/llamaapi.md
docs/user-guide/concepts/model-providers/ollama.md
docs/user-guide/concepts/model-providers/openai.md

Adding documentation on how to build structured_output in the Custom model provider docs, and updated existing model providers with info on how to use it.
https://github.com/strands-agents/docs/issues/95
Give users info on how to build the structured output feaature into their model providers
All Model Provider docs
N/A
N/A

Update structured output docs for model providers

---

docs/user-guide/observability-evaluation/traces.md

Updated tracer setup guide based on the changes [here](https://github.com/strands-agents/sdk-python/pull/316)
- Allow chaining
- Allow passing tracer_provider
Tracer
NA

docs: updated tracer setup guide

---

docs/user-guide/concepts/model-providers/mistral.md
mkdocs.yml

Add documentation support for Mistral AI Provider
The model provider page
This PR is related to: https://github.com/strands-agents/sdk-python/pull/284
The test to check documentation for this doc are failing as the Mistral model in strands-sdk is not merged yet
Getting this error:
```ERROR   -  mkdocstrings: strands.models.mistral could not be found
ERROR   -  Error reading page 'api-reference/models.md':
ERROR   -  Could not collect 'strands.models.mistral'
Aborted with a BuildError!```

[docs] add Mistral AI provider documentation(Do not merge)

---

docs/user-guide/concepts/agents/agent-loop.md
docs/user-guide/concepts/agents/prompts.md
docs/user-guide/concepts/agents/state-sessions.md
docs/user-guide/concepts/tools/tools_overview.md
docs/user-guide/quickstart.md
mkdocs.yml

Documentation for the newly added AgentState feature: https://github.com/strands-agents/sdk-python/pull/292
AgentState will be used in the upcoming SessionPersistence feature request: https://github.com/strands-agents/sdk-python/issues/246
session-state.md, and other files that link to this
N/A

Add Agent State to docs

---

docs/user-guide/concepts/agents/hooks.md
mkdocs.yml

Document the concept of hooks, what hooks are available, and how to use them
New content addition

Add hooks documentation

---

docs/api-reference/event-loop.md
docs/user-guide/observability-evaluation/logs.md

Recently removed message_processor from sdk, so fixing the docs buid.
- Bug fix
bug fix for build
N/A
https://unshure.github.io/docs/latest/

Remove message_processor from api-reference

---

docs/api-reference/handlers.md
docs/api-reference/models.md
docs/api-reference/types.md
docs/user-guide/concepts/agents/agent-loop.md
docs/user-guide/concepts/model-providers/custom_model_provider.md
docs/user-guide/quickstart.md

We have moved the abstract model class from types into the models subpackage. For more details, please see https://github.com/strands-agents/sdk-python/pull/409.
Note, the workflow is failing with the error:
```
ERROR   -  mkdocstrings: strands.models.model could not be found
ERROR   -  Error reading page 'api-reference/models.md':
ERROR   -  Could not collect 'strands.models.model'
```
This will be resolved once the above PR is released into PyPI.

models - move abstract class

---

docs/user-guide/concepts/model-providers/custom_model_provider.md
requirements.txt

- Updated Strands Agents SDK version
- Updated the custom model provider documentation to reflect the current stream-first model interface. Rewrote the implementation guide to focus on the single `stream` method entry point, clarified that helper methods are optional recommendations rather than requirements, and removed references to historical interface changes to maintain focus on current functionality.
See related feature PR in SDK: https://github.com/strands-agents/sdk-python/pull/400
**Content update/revision**
The documentation was referencing an outdated model interface pattern and needed to be updated to match the current SDK implementation. The previous documentation referenced abstract methods that are no longer required.
This update ensures developers have accurate, current …

docs(model): update model provider documentation to match the new interface

---

docs/api-reference/multiagent.md

add API reference section for strands.multiagent.swarm module
document Swarm in API reference (https://github.com/strands-agents/sdk-python/pull/416)
https://strandsagents.com/latest/api-reference/multiagent/ (pending deployment)
N/A
N/A

docs(multiagent): add API reference section for strands.multiagent.swarm module

---

docs/user-guide/concepts/model-providers/custom_model_provider.md

Update of docs to account for strands-agents/sdk-python/pull/466 which fixes strands-agents/sdk-python#362
- Bug fix
N/A

Update docs to account for system_prompt in structured_output

---

docs/examples/deploy_to_eks/README.md
docs/user-guide/concepts/model-providers/amazon-bedrock.md
docs/user-guide/concepts/model-providers/anthropic.md
docs/user-guide/observability-evaluation/evaluation.md
docs/user-guide/observability-evaluation/logs.md
docs/user-guide/observability-evaluation/traces.md
docs/user-guide/quickstart.md

Docs change for strands-agents/sdk-python/pull/467 where we're updating the default bedrock model to be Claude 4.

Update docs to reference 4.0 as the default model

---

docs/user-guide/safety-security/pii-redaction.md

This page provides PII user guide 
- Bug fix
new content.
- [ x] I have read the CONTRIBUTING document
- [ x] My changes follow the project's documentation style
- [ x] I have tested the documentation locally using `mkdocs serve`
- [ x] Links in the documentation are valid and working
- [ x] All new and existing tests pass

add PII-Redaction user guide

---

docs/README.md
docs/examples/python/meta_tooling.md
requirements.txt

default model changed to claude 4 sonnet
Default model changed to Claude 4 Sonnet with v1.0.0
Welcome page. All other references are already updated: https://github.com/search?q=repo%3Astrands-agents%2Fdocs%203.7&type=code
N/A
N/A

docs(welcome): default model changed to claude 4 sonnet

---

docs/user-guide/concepts/multi-agent/agent-to-agent.md

This is a minor refactor to only have one agent invocation running in the docs. Otherwise, the output is a bit confusing when run without changes.
This is a companion PR to https://github.com/strands-agents/tools/pull/165

docs(a2a): revise a2a tool section

---

docs/user-guide/concepts/tools/python-tools.md

Several comments have been made about leveraging the tool decorator within classes. Strands already supports this use case and even implemented some of its tools using the strategy (e.g. [browser](https://github.com/strands-agents/tools/blob/main/src/strands_tools/browser/browser.py#L53)). We have not documented this, though, which leaves customers in the dark. This PR promotes the new class based approach.
PR for #110 which will allow us to close out https://github.com/strands-agents/sdk-python/pull/162
Tools

feat(tools): add class based python tools section

---

docs/user-guide/concepts/streaming/async-iterators.md
docs/user-guide/concepts/streaming/callback-handlers.md

document redactedContent event type introduced in https://github.com/strands-agents/sdk-python/issues/99
New SDK feature.
- Streaming / Async Iterators
- Streaming / Callback Handlers
N/A
N/A

docs(streaming): document redactedContent event type

---

docs/user-guide/concepts/agents/state.md
docs/user-guide/concepts/tools/example-tools-package.md

Just updating the tools documentation page to be more up to date with all the new tools added to the tools repository.
Updating the Example Built-In Tools page. 

fix: Updating Strands Tools documentation page

---

docs/user-guide/concepts/agents/agent-loop.md

Documentation corresponding with https://github.com/strands-agents/sdk-python/pull/576
This adds guidance for the common problem of orphaned tool blocks which will now be caught and rethrown as a maxtokens exception
https://github.com/strands-agents/sdk-python/discussions/541
Agent-Loop
- [n/a] Links in the documentation are valid and working
- [n/a] Images/diagrams are properly sized and formatted

docs(agent-loop): add troubleshooting to agent loop section

---

docs/user-guide/concepts/tools/example-tools-package.md

On example tool package page, web and network section - https://strandsagents.com/latest/documentation/docs/user-guide/concepts/tools/example-tools-package/?h=browser#web-network
I changed that tool path to browser/browser.py (https://github.com/strands-agents/tools/blob/main/src/strands_tools/browser/browser.py)
The link of browser tools is not found - https://github.com/strands-agents/tools/blob/main/src/strands_tools/browser.py
So, I changed that tool path to browser/browser.py (https://github.com/strands-agents/tools/blob/main/src/strands_tools/browser/browser.py)
1. https://strandsagents.com/latest/documentation/docs/user-guide/concepts/tools/example-tools-package/
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

fix: update browser tool path in documentation

---

docs/user-guide/concepts/agents/hooks.md

Fix minor bug called out in https://github.com/strands-agents/docs/issues/196 where hooks is not defined, since it should be called using the agent object.
https://github.com/strands-agents/docs/issues/196
https://strandsagents.com/latest/documentation/docs/user-guide/concepts/agents/hooks/#registering-individual-hook-callbacks

fix(hooks): clarify that hooks is accessible through agent object

---

CONTRIBUTING.md

Update instructions on finding issues in `sdk-python` and `tools` with the label "Ready for Contribution". 

feat: Modify Contributing guide to add instructions for finding issues that are ready for contribution

---

docs/user-guide/concepts/model-providers/anthropic.md
docs/user-guide/concepts/model-providers/cohere.md
docs/user-guide/concepts/model-providers/litellm.md
docs/user-guide/concepts/model-providers/llamaapi.md
docs/user-guide/concepts/model-providers/mistral.md
docs/user-guide/concepts/model-providers/ollama.md
docs/user-guide/concepts/model-providers/openai.md
docs/user-guide/concepts/model-providers/sagemaker.md
docs/user-guide/concepts/model-providers/writer.md

When following the model provider example, the calculator tool is used, which depends on the strands-agents-tools package. This package is not currently mentioned in the documentation.
This PR updates the installation instructions to include strands-agents-tools in the pip command, ensuring users can run the example without missing dependency errors.
- Bug fix
This PR updates the installation instructions to include strands-agents-tools in the pip command, ensuring users can run the example without missing dependency errors.
The model provider example in the documentation uses the calculator tool, which depends on the strands-agents-tools package. Since …

docs: fix install command for strands-agents-tools package

---

docs/user-guide/concepts/tools/tools_overview.md

Follow-up to #194 where examples were not using keyword arguments and thus not working correctly.
strands-agents/tools#194 revealed that our docs should call out to always use keyword parameters
Tools overview
N/A

fix: Call-out that direct method calls must used keyword arguments

---

docs/api-reference/tools.md

Temporarily remove reference for tools executor from docs

---

docs/user-guide/quickstart.md

We receive a lot of questions about the default output behavior, so putting this up front in the QuickStart
Content update/revision
We receive a lot of questions about the default output behavior, so putting this up front in the QuickStart.  Semi related to discoverability and strands-agents/sdk-python/issues/506

Document the Console Output default behavior

---

README.md

Updates the README installation instructions to use `pip install .` instead of `pip install -r requirements.txt`, aligning with the project's migration to pyproject.toml.
In commit d7bc993 (PR #225), the project switched from using requirements.txt to pyproject.toml for dependency management. However, the README was never updated to reflect this change, causing confusion for new contributors following the setup instructions.
- Updated installation command from `pip install -r requirements.txt` to `pip install .`
- Maintains all other setup instructions unchanged
Fixes the outdated installation instructions and ensures consistency with the current project structure.

fix: installation instructions to reflect switchover to pyproject.toml

---

docs/examples/python/structured_output.py

This PR resolves a permission error that occurs when running the structured_output.py example on Windows operating systems.
- Bug fix
When executing the multimodal example on Windows, a PermissionError: [Errno 13] Permission denied is encountered. This occurs because the code attempts to open the same temporary file twice simultaneously - once through the NamedTemporaryFile context manager and again with open(person_file.name, "rb").
Windows operating system enforces exclusive file access, preventing multiple handles from accessing the same file concurrently. This restriction causes the second file opening operation to fail with a permission error.
Adding delete=False to the NamedTemporaryFile constructor resolves this issue by allowing the file to remain accessible after the initial …

a minor fix to structured_output example for running on window OS

---

docs/user-guide/concepts/tools/python-tools.md

Add a section on tools yielding events back up to the caller.  This documents the implementation of strands-agents/sdk-python/issues/543
Currently tool streaming is un-documented; this fixes that and completes strands-agents/sdk-python/issues/543
python-tools

Document tool streaming

---

docs/user-guide/concepts/tools/python-tools.md

Follow-up to strands-agents/sdk-python/pull/761 for sdk-python/issues/579, add documentation detailing how invocation state can be passed and retrieved in decorated tools

feat: Add documentation for ToolContext.invocation_state

---

docs/user-guide/concepts/multi-agent/agent-to-agent.md

Adding a section for A2A agent as tool. This is a common pattern when devs want to implement orchestrator pattern through A2A.
Customer reachouts/questions
A2A

docs(a2a): Add A2A agent as tool

---

docs/api-reference/models.md
docs/user-guide/concepts/model-providers/gemini.md
mkdocs.yml

Added documentation for Google Gemini model integration ([Commit](https://github.com/strands-agents/sdk-python/commit/54bc162fb6b2ebfdd719204344e206db359260d6)), keeping it consistent with the other model provider documentations.
The Gemini model support was recently merged into the SDK but lacked documentation. This PR adds complete documentation to help users understand how to integrate and use Google Gemini models with the Strands framework, 
including configuration options, authentication setup, and practical usage examples.
• docs/api-reference/models.md - Added Gemini model API reference
• docs/user-guide/concepts/model-providers/gemini.md - Added comprehensive Gemini user guide with examples
• Updated package dependencies to include latest SDK version with Gemini support
Since this …

feat: add page for Gemini model provider documentation

---

docs/user-guide/concepts/agents/hooks.md
docs/user-guide/concepts/multi-agent/graph.md
docs/user-guide/concepts/multi-agent/multi-agent-patterns.md
docs/user-guide/concepts/multi-agent/swarm.md
docs/user-guide/concepts/tools/python-tools.md

This PR documents the new multi-agent shared state feature that allows passing `invocation_state` to Graph and Swarm patterns. The feature enables sharing configuration, credentials, and context data across all agents in multi-agent patterns without exposing this information to the LLM.
Following the implementation of PR [#816 in the SDK](https://github.com/strands-agents/sdk-python/pull/816), this documentation update is needed to help developers understand how to use the new `invocation_state` parameter with multi-agent patterns. The feature addresses a key customer need for sharing configuration and credentials across agents while maintaining proper separation of concerns.
The original SDK PR introduced kwargs support to Graph and Swarm, allowing developers to pass shared state that …

Add multi-agent shared state docs
