- docs/user-guide/concepts/multi-agent/graph.md
- docs/user-guide/concepts/multi-agent/swarm.md
- mkdocs.yml
Update doc links to point at correct urls; links haven't been tested due to the repository issue.
- Bug fix
> Update doc links to point at correct urls

- docs/stylesheets/extra.css
- mkdocs.yml
Additions:
- Update color scheme & toggle icons
- Lighten the text font in dark mode
Light mode:
Dark mode:
> Update theme with feedback from team

- docs/examples/python/memory_agent.md
- docs/examples/python/memory_agent.py
Adding an example of using `mem0_memory` as a tool with strands Agent.
> Add example using mem0_memory tool

- docs/user-guide/concepts/model-providers/amazon-bedrock.md
note AWS_REGION environment variable
Documentation for `AWS_REGION` issue reported in https://github.com/strands-agents/sdk-python/issues/38.
https://strandsagents.com/0.1.x/user-guide/concepts/model-providers/amazon-bedrock/
> docs(bedrock): note AWS_REGION environment variable

- docs/user-guide/concepts/model-providers/llamaapi.md
Meta wants to track the origin of users.
To achieve this, we propose modifying the llama-api website link to record user referrals.
> docs: update url link

- docs/examples/python/cli-reference-agent.md
Fix cli documentation
- Bug fix
Typo
https://github.com/strands-agents/agent-builder/issues/5
CLI example
N/A
N/A
> update cli docs

- docs/user-guide/safety-security/guardrails.md
Update code sample to include guardrail protected BedrockModel in the agent
- Bug fix
https://strandsagents.com/latest/user-guide/safety-security/guardrails/#amazon-bedrock
- [-] Images/diagrams are properly sized and formatted
> fix(guardrails): update code sample to include guardrail protected BedrockModel in the agent

- docs/assets/logo-light.svg
fix light logo color scheme
- Bug fix
- Assets
> fix(logo): fix light logo color scheme

- docs/stylesheets/extra.css
- mkdocs.yml
Change color schemes to black/white.
- Style and theme
All docs pages.
> style(theme): change to black/white theme

- .gitignore
- docs/examples/README.md
- docs/examples/deploy_to_eks/README.md
- docs/examples/deploy_to_eks/chart/.helmignore
- docs/examples/deploy_to_eks/chart/Chart.yaml
- docs/examples/deploy_to_eks/chart/templates/NOTES.txt
- docs/examples/deploy_to_eks/chart/templates/_helpers.tpl
- docs/examples/deploy_to_eks/chart/templates/deployment.yaml
- docs/examples/deploy_to_eks/chart/templates/ingress.yaml
- docs/examples/deploy_to_eks/chart/templates/poddisruptionbudget.yaml
- docs/examples/deploy_to_eks/chart/templates/service.yaml
- docs/examples/deploy_to_eks/chart/templates/serviceaccount.yaml
- docs/examples/deploy_to_eks/chart/values.yaml
- docs/examples/deploy_to_eks/docker/Dockerfile
- docs/examples/deploy_to_eks/docker/app/app.py
- docs/examples/deploy_to_eks/docker/requirements.txt
- docs/user-guide/deploy/deploy_to_amazon_eks.md
- docs/user-guide/deploy/operating-agents-in-production.md
- mkdocs.yml
Deploying strands-agents weather application on Amazon EKS
There was no example on deploying strands agents on Amazon EKS
resolves issue #52 
user-guide
> docs: deploying on Amazon EKS

- mkdocs.yml
- requirements.txt
#77 reverted the original implementation of llms.txt because it broke mermaid diagram rendering; this restores the original LLM changes + fixes the mermaid rendering issue by including it as extra-javascript.
I also removed a duplicate requirement of mkdocs-macros-plugin
New content addition
#72 initially implemented this but was reverted in #77 
A version of the docs are at https://github.programdotrun.com/docs/latest/llms.txt
Mermaid diagram: https://github.programdotrun.com/docs/latest/user-guide/concepts/agents/agent-loop/
LLMS txt https://github.programdotrun.com/docs/latest/llms.txt
> Auto generate llms.txt + fix mermaid issue

- .github/workflows/build-deploy.yml
Minor version bump
- Bug fix
version bump
Releasing minor version bump
N/A
https://unshure.github.io/docs/0.2.x/
> Bump docs version

- docs/user-guide/concepts/multi-agent/agent-to-agent.md
Updates from bug bash to include updated timeout and remove 'native'
> fix(a2a): add timeout and remove "native"

- docs/user-guide/concepts/multi-agent/graph.md
- docs/user-guide/concepts/multi-agent/swarm.md
docs pages for Swarm + Graph
https://github.com/strands-agents/sdk-python/issues/214
Introducing Graph and Swarm multi-agent orchestrators
* https://strandsagents.com/latest/user-guide/concepts/multi-agent/swarm/
* https://strandsagents.com/latest/user-guide/concepts/multi-agent/graph/
N/A
> docs(multiagent): docs pages for Swarm + Graph

- docs/user-guide/deploy/deploy_to_bedrock_agentcore.md
- mkdocs.yml
> docs(agentcore): deploy

- docs/examples/python/multi_agent_example/multi_agent_example.md
- docs/examples/python/multimodal.md
- docs/user-guide/concepts/model-providers/cohere.md
- docs/user-guide/concepts/model-providers/ollama.md
- docs/user-guide/concepts/tools/example-tools-package.md
- docs/user-guide/deploy/deploy_to_amazon_eks.md
- docs/user-guide/deploy/deploy_to_bedrock_agentcore.md
No change of meaning of any content. Just fixing typos: see commit diffs for details.
Improve doc quality
N/A
N/A
N/A
> fixing various typos

- docs/stylesheets/extra.css
- docs/user-guide/quickstart.md
- mkdocs.yml
* add observability section
* link to logs docs
* link to Cohere model provider
* reference Bedrock API keys
* update strands-agents and strands-agents-tools versions in snippet
Observability is an important topic that customers frequently ask about. Referencing this in our quick start makes it more discoverable.
https://strandsagents.com/latest/documentation/docs/user-guide/quickstart/
N/A
N/A
> updates to quickstart page

- docs/user-guide/deploy/deploy_to_bedrock_agentcore.md
> fix minor display error

- docs/user-guide/deploy/operating-agents-in-production.md
Added Bedrock AgentCore to Deployment patterns section
This was missed as part of the original Bedrock Agent Core documentation
Operating Agents in production section
> chore: Added Bedrock AgentCore to Deployment patterns section

- docs/user-guide/concepts/model-providers/ollama.md
https://github.com/strands-agents/docs/issues/194
llama3 doesn't suppor tool use, bump to 3.1. Tested all examples, no bugs or errors
- Bug fix
- [ x] I have read the CONTRIBUTING document
- [ x] My changes follow the project's documentation style
- [ x] I have tested the documentation locally using `mkdocs serve`
- [ x] Links in the documentation are valid and working
- [ x] Images/diagrams are properly sized and formatted
- [ x] All new and existing tests pass
> Update Ollama model to 3.1 in our example

- docs/user-guide/concepts/agents/state.md
Update examples to use tool context. The current examples do not work since v1.0 
- 
Examples are outdated and not working 
Agent state
> docs(state): Update examples to use tool context

- docs/user-guide/concepts/multi-agent/graph.md
Added explanation for how multiple conditional edges are handled in graphs.
Customer reachout/question
Graph
> fix(graph): Add multiple conditional edges evaluation explanation
